# TUPLAS (Tuplas são imutaveis)

lanche = ('hamburguer', 'Suco', 'Pizza', 'Pudim', 'Batata Frita')
print(lanche)
print(lanche[1])
print(lanche[3])
print(lanche[-2])
print(lanche[1:3])
print(lanche[2:])
print(lanche[:2])
print(lanche[-2:])
print('=' * 36)
for cont in range(0, len(lanche)):
    print(f'Eu vou comer {lanche[cont]} ')
print('=' * 36)
for comida in lanche:
    print(f'Eu vou comer {comida}')
print('=' * 36)
for cont in range(0, len(lanche)):
    print(f'Eu vou comer {lanche[cont]} na posição {cont} ')
print('=' * 36)
for pos, comida in enumerate(lanche):
    print(f'Eu vou comer {comida} na posição{pos}')
print('=' * 36)
print(sorted(lanche))
print('=' * 36)
print('Comi pra caramba!')
print('=' * 36)
a = (2, 5, 4)
b = (5, 8, 1, 2)
c = b + a
print(a)
print(b)
print(c)
print(len(c))
print(c.count(5))
print('=' * 36)
print(c)
print(c.index(5))
print('=' * 36)
pessoa = ('Roberto', 40, 'M', 102.7)
print(pessoa)
print('=' * 36)
# del delete uma tupla inteira
#del(pessoa)
#print(pessoa)
print('=' * 36)
